#!/bin/bash
set -euo pipefail

# update-segment -- Segment release script.
#
# Edward Smith, October 2017

scriptname=$(basename "${BASH_SOURCE[0]}")
scriptpath="${BASH_SOURCE[0]}"
scriptpath=$(cd "$(dirname "${scriptpath}")" && pwd)
cd "${scriptpath}"

# Make sure the version, podspec, and CHANGELOG.md are all updated.
version=0.1.7

edit Segment-Branch.podspec
edit CHANGELOG.md
edit update-segment
echo ">>> update-segment"
echo ">>> Check that the version is updated in:"
echo ">>> 'Segment-Branch.podspec', 'CHANGELOG.md', and 'update-segment'."
askYN "Continue?"

# Make sure the example compiles:

phone="iPhone 7 Plus"
phoneOS="latest"

echo ">>> Building Example..."
cd Example
pod install
pod update
xcodebuild \
    -workspace Segment-Branch.xcworkspace \
    -scheme Segment-Branch-Example \
    -destination name="$phone",OS="$phoneOS" \
    -quiet \
    clean build

# Commit to git and push podspec:

cd ..
echo ">>> Committing to git and pushing podspec."
git add --all
git commit -m "Prepare for release ${version}."
git tag -a "$version" -m "Version ${version}"
git push && git push --tags
pod trunk push Segment-Branch.podspec --allow-warnings

echo ">>> Check the version number at Cocoapds.org."
open "https://cocoapods.org/pods/Segment-Branch"
