source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Segment-Branch_Example' do
  pod "Segment-Branch", :path => "../../"
end

target 'Segment-Branch_Tests' do
  pod "Segment-Branch", :path => "../../"

  pod 'Specta'
  pod 'Expecta'
end
